In [1]:
import numpy as np
import sys, os
diage_path = os.environ.get('DIAGE','')

path = diage_path+'/class'
sys.path.append(path)
from ClassDiagE import Crystal as cr
from ClassDiagE import FHamiltonian as fh
from ClassDiagE import BHamiltonian as bh
from ClassDiagE import FT_grid as ft
from ClassDiagE import Method
from ClassDiagE import Impurity
path = diage_path+'/modules'
sys.path.append(path)
import DiagE
import os

/Users/moseongjun/Desktop/DiagE/class/ClassDiagE.py:864: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if (self.ns is not 1):


In [2]:
latt = [[1,0,0],[0,1,0],[0,0,1]]
pos = [[0,0,0],[1/2,1/2,0],[1/2,1/2,1/2]]
temp = cr(latt,pos)
grid = [5,5,5]
temp.Kpoint(meshgrid=grid)

In [3]:
ftemp = fh(temp,1)
orboption1 = [0,5]
orboption2 = [1,5]
orboption3 = [2,3]
ftemp.set_basis_index(orboption1)
ftemp.set_basis_index(orboption2)
ftemp.set_basis_index(orboption3)
ftemp.find

{0: [0, 0],
 1: [0, 1],
 2: [0, 2],
 3: [0, 3],
 4: [0, 4],
 5: [1, 0],
 6: [1, 1],
 7: [1, 2],
 8: [1, 3],
 9: [1, 4],
 10: [2, 0],
 11: [2, 1],
 12: [2, 2]}

In [4]:
btemp = bh(temp,ftemp)
btemp.set_basis_index(orboption1)
btemp.set_basis_index(orboption2)
btemp.set_basis_index(orboption3)
btemp.bind

{0: [0, [0, 0]],
 1: [0, [0, 1]],
 2: [0, [0, 2]],
 3: [0, [0, 3]],
 4: [0, [0, 4]],
 5: [0, [1, 0]],
 6: [0, [1, 1]],
 7: [0, [1, 2]],
 8: [0, [1, 3]],
 9: [0, [1, 4]],
 10: [0, [2, 0]],
 11: [0, [2, 1]],
 12: [0, [2, 2]],
 13: [0, [2, 3]],
 14: [0, [2, 4]],
 15: [0, [3, 0]],
 16: [0, [3, 1]],
 17: [0, [3, 2]],
 18: [0, [3, 3]],
 19: [0, [3, 4]],
 20: [0, [4, 0]],
 21: [0, [4, 1]],
 22: [0, [4, 2]],
 23: [0, [4, 3]],
 24: [0, [4, 4]],
 25: [1, [0, 0]],
 26: [1, [0, 1]],
 27: [1, [0, 2]],
 28: [1, [0, 3]],
 29: [1, [0, 4]],
 30: [1, [1, 0]],
 31: [1, [1, 1]],
 32: [1, [1, 2]],
 33: [1, [1, 3]],
 34: [1, [1, 4]],
 35: [1, [2, 0]],
 36: [1, [2, 1]],
 37: [1, [2, 2]],
 38: [1, [2, 3]],
 39: [1, [2, 4]],
 40: [1, [3, 0]],
 41: [1, [3, 1]],
 42: [1, [3, 2]],
 43: [1, [3, 3]],
 44: [1, [3, 4]],
 45: [1, [4, 0]],
 46: [1, [4, 1]],
 47: [1, [4, 2]],
 48: [1, [4, 3]],
 49: [1, [4, 4]],
 50: [2, [0, 0]],
 51: [2, [0, 1]],
 52: [2, [0, 2]],
 53: [2, [1, 0]],
 54: [2, [1, 1]],
 55: [2, [1, 2]],
 5

In [5]:
beta = 38
size = 1000
FT = ft(beta,size)
FT.Tau()
FT.Nu()
FT.Omega()


In [6]:
itemp = Impurity(ftemp,btemp,FT)

In [7]:
input_dict = {"1" : [[[0,0],[0,1]],[[1,0],[1,2]]],"2" : [[[2,0],[2,1],[2,2]]]}

In [8]:
equiv = [[1,1],[1,1,2]]
import numpy as np
for ii in range(2):
    e_mat = np.diag(equiv[ii])
    print(e_mat)

[[1 0]
 [0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 2]]


In [9]:
a = 0
b = 0
for key, val in input_dict.items():
    a += len(val)
    for orb in val:
        if len(orb)>=b:
            b = len(orb)
        # print(b)
print(a,b)

3 3


In [10]:
itemp.projector(input_dict)

0 0 0 0
1 1 0 0
5 0 1 1
7 1 1 1
10 0 0 2
11 1 0 2
12 2 0 2


In [11]:
itemp.fermion.prob_space

{'1': [0, 1], '2': [2]}

In [12]:
for ispace in range(itemp.bprojector.shape[3]):
    for js in range(itemp.bprojector.shape[2]):
        for iorbc in range(itemp.bprojector.shape[1]):
            for iorb in range(itemp.bprojector.shape[0]):
                if itemp.bprojector[iorb,iorbc,js,ispace] == 1:
                    print(iorb,iorbc,js,ispace)

0 0 0 0
1 1 0 0
5 2 0 0
6 3 0 0
25 0 0 1
27 1 0 1
35 2 0 1
37 3 0 1
50 0 0 2
51 1 0 2
52 2 0 2
53 3 0 2
54 4 0 2
55 5 0 2
56 6 0 2
57 7 0 2
58 8 0 2


In [13]:
btemp.prob_space

{'1': [0, 1], '2': [2]}

In [14]:
for key, val in itemp.prob_space.items():
    nn = len(val)
    # for ii in range(nn):
    for ii, kk in enumerate(val):
        print(ii,kk)
        for ind in itemp.fermion.imp_dict[key][ii]:
            print(ind,itemp.fermion.imp_dict[key][ii].index(ind))

In [15]:
itemp.fprojector.shape

(13, 3, 1, 3)

In [16]:
a = sum(len(l) for l in ftemp.imp_dict['1'])
a

4

In [17]:
itemp.bprojector.shape

(59, 9, 1, 3)

In [18]:
temp = {}
for key, val in input_dict.items():
    temp[key] = []
    for ind in val:
        print(ind)
        temp_list = []
        for orb in ind:
            print(orb)
            a = ftemp.Findex(orb)
            temp_list.append(a)
        temp[key].append(temp_list)
temp

[[0, 0], [0, 1]]
[0, 0]
[0, 1]
[[1, 0], [1, 2]]
[1, 0]
[1, 2]
[[2, 0], [2, 1], [2, 2]]
[2, 0]
[2, 1]
[2, 2]


{'1': [[0, 1], [5, 7]], '2': [[10, 11, 12]]}

In [19]:
itemp.fermion.imp_dict

{'1': [[0, 1], [5, 7]], '2': [[10, 11, 12]]}

In [20]:
itemp.boson.imp_dict

{'1': [[0, 1, 5, 6], [25, 27, 35, 37]],
 '2': [[50, 51, 52, 53, 54, 55, 56, 57, 58]]}

In [21]:
itemp.bprojector[:,:,0,0]

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0.

In [22]:
# for key, val in itemp.imp_dict.items():
#     nn = len(itemp.imp_dict[key])
#     print(itemp.imp_dict[key])
#     for ii in range(nn):
#         orb = itemp.imp_dict[key][ii]
#         print(itemp.imp_dict[key][ii])
#         for iorb in orb:
#             for jorb in orb:
#                 print(btemp.b2f.index([iorb,jorb]))

In [23]:
def FimpconvertLocStc(mat : np.ndarray,flag, input_dict : dict):

    norb = mat.shape[0]
    ns = mat.shape[2]
    nprob = mat.shape[3]
    
    mat_ret = np.zeros((norb,norb,ns,nprob),dtype=complex,order='F')

    if flag == 1:
        
        for key, val in input_dict.items():
            nn = len(input_dict[key])
            iprob = int(key)-1
            orb1 = input_dict[key][0]
            for js in range(ns):
                print(orb1)
                for ii in range(0,nn):
                    orb2 = input_dict[key][ii]
                    print(orb2)
                    for iorb2 in orb2:
                        for jorb2 in orb2:
                            for iorb1 in orb1:
                                for jorb1 in orb1:
                                    mat_ret[iorb2,jorb2,js,iprob] = mat[iorb1,jorb1,js,iprob]
        return mat_ret
    
    elif flag == 0:
        for key, val in input_dict.items():
            iprob = int(key)-1
            for js in range(ns):
                orb1 = input_dict[key][0]
                print(orb1)
                for iorb1 in orb1:
                    for jorb1 in orb1:
                        mat_ret[iorb1,jorb1,js,iprob] = mat[iorb1,jorb1,js,iprob]
        
        return mat_ret
        

    

In [24]:
itemp.fprojector.shape

(13, 3, 1, 3)

In [25]:
tempmat = np.zeros((13,13,1,2),dtype=complex,order='F')

for ii in range(2):
    for jj in range(2):
        tempmat[ii,jj,0,0] = 1
for ii in range(10,12):
    for jj in range(10,12):
        tempmat[ii,jj,0,1] = 1

In [26]:
tempmat_loc_dyn = np.zeros((13,13,1,100,2),dtype=complex,order='F')

for ii in range(100):
    tempmat_loc_dyn[:,:,:,ii,:] = tempmat

In [27]:
tempmat_loc_dyn1 = ftemp.FimpconvertLocDyn(tempmat_loc_dyn,1)

In [28]:
tempmat_loc_dyn2=ftemp.FimpconvertLocDyn(tempmat_loc_dyn1,0)

In [29]:
temp = tempmat_loc_dyn-tempmat_loc_dyn2

In [30]:
temp.min()

0j

In [31]:
tempmat[5,5,0,0]

0j

In [32]:
tempmat1 = FimpconvertLocStc(tempmat,1,ftemp.imp_dict)

[0, 1]
[0, 1]
[5, 7]
[10, 11, 12]
[10, 11, 12]


In [33]:
a = tempmat1[:,:,0]

for iprob in range(2):
    for ii in range(13):
        for jj in range(13):
            if a[ii,jj,iprob] == 1.0:
                print(ii,jj,iprob)

0 0 0
0 1 0
1 0 0
1 1 0
5 5 0
5 7 0
7 5 0
7 7 0


In [34]:
for key in ftemp.imp_dict.keys():
    print(int(key))
    

1
2


In [35]:
tempmat2 = FimpconvertLocStc(tempmat,0,ftemp.imp_dict)

[0, 1]
[10, 11, 12]


In [36]:
norb = tempmat.shape[0]
ns = tempmat.shape[2]
nprob = tempmat.shape[3]

for iprob in range(nprob):
    for js in range(ns):
        for iorb in range(norb):
            for jorb in range(norb):
                if abs(tempmat[iorb,jorb,js,iprob]-tempmat2[iorb,jorb,js,iprob])>=1.0e-6:
                    print(iorb,jorb,js,iprob,abs(tempmat[iorb,jorb,js,iprob]-tempmat2[iorb,jorb,js,iprob]),tempmat[iorb,jorb,js,iprob],tempmat2[iorb,jorb,js,iprob])

In [37]:
btemp.imp_dict

{'1': [[0, 1, 5, 6], [25, 27, 35, 37]],
 '2': [[50, 51, 52, 53, 54, 55, 56, 57, 58]]}

In [38]:
tempmat3 = np.zeros((len(btemp.bind),len(btemp.bind),1,1,2),dtype=complex,order='F')

for key, val in btemp.imp_dict.items():
    iprob = int(key)-1
    for iorb in val[0]:
        for jorb in val[0]:
            tempmat3[iorb,jorb,0,0,iprob] = 1


In [39]:
tempmat4 = btemp.BimpconvertLocStc(tempmat3,1)
tempmat5 = btemp.BimpconvertLocStc(tempmat4,0)
temp = tempmat3-tempmat5
temp.max()

0j

In [40]:
cnt = 0
for iprob in range(2):
    for ii in range(59):
        for jj in range(59):
            if tempmat3[ii,jj,0,0,iprob] == 1:
                print(ii,jj,iprob,tempmat3[ii,jj,0,0,iprob])
                cnt+=1
print(cnt)

0 0 0 (1+0j)
0 1 0 (1+0j)
0 5 0 (1+0j)
0 6 0 (1+0j)
1 0 0 (1+0j)
1 1 0 (1+0j)
1 5 0 (1+0j)
1 6 0 (1+0j)
5 0 0 (1+0j)
5 1 0 (1+0j)
5 5 0 (1+0j)
5 6 0 (1+0j)
6 0 0 (1+0j)
6 1 0 (1+0j)
6 5 0 (1+0j)
6 6 0 (1+0j)
50 50 1 (1+0j)
50 51 1 (1+0j)
50 52 1 (1+0j)
50 53 1 (1+0j)
50 54 1 (1+0j)
50 55 1 (1+0j)
50 56 1 (1+0j)
50 57 1 (1+0j)
50 58 1 (1+0j)
51 50 1 (1+0j)
51 51 1 (1+0j)
51 52 1 (1+0j)
51 53 1 (1+0j)
51 54 1 (1+0j)
51 55 1 (1+0j)
51 56 1 (1+0j)
51 57 1 (1+0j)
51 58 1 (1+0j)
52 50 1 (1+0j)
52 51 1 (1+0j)
52 52 1 (1+0j)
52 53 1 (1+0j)
52 54 1 (1+0j)
52 55 1 (1+0j)
52 56 1 (1+0j)
52 57 1 (1+0j)
52 58 1 (1+0j)
53 50 1 (1+0j)
53 51 1 (1+0j)
53 52 1 (1+0j)
53 53 1 (1+0j)
53 54 1 (1+0j)
53 55 1 (1+0j)
53 56 1 (1+0j)
53 57 1 (1+0j)
53 58 1 (1+0j)
54 50 1 (1+0j)
54 51 1 (1+0j)
54 52 1 (1+0j)
54 53 1 (1+0j)
54 54 1 (1+0j)
54 55 1 (1+0j)
54 56 1 (1+0j)
54 57 1 (1+0j)
54 58 1 (1+0j)
55 50 1 (1+0j)
55 51 1 (1+0j)
55 52 1 (1+0j)
55 53 1 (1+0j)
55 54 1 (1+0j)
55 55 1 (1+0j)
55 56 1 (1+0j)
55 57 1 (1+0

In [42]:
btemp.prob_space

{'1': [0, 1], '2': [2]}